# -------- This file is automatically generated by LSST's sconsUtils -------- #
__version__ = 'a57aaf9'
__repo_version__ = 'a57aaf9'
__fingerprint__ = 'a57aaf9699abcdba93b824b729323b609a272d12 *'
__dependency_versions__ = {
}
__all__ = (
    '__version__',
    '__repo_version__',
    '__fingerprint__',
    '__dependency_versions__',
)
