{% set data= load_setup_py_data() %}
package:
  name: ts-atwhitelight
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  noarch: python

test:
  requires:
    - ts-conda-build =0.3
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - ts-tcpip
    - labjack-ljm
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python {{ python }}
    - numpy {{ numpy }}
    - setuptools {{ setuptools }}
    - setuptools_scm {{ setuptools_scm }}
    - ts-salobj
    - ts-tcpip
