{% set data= load_setup_py_data() %}
package:
  name: ts-atwhitelight
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - command_atwhitelight = lsst.ts.atwhitelight:command_atwhitelight
    - run_atwhitelight = lsst.ts.atwhitelight:run_atwhitelight

  script_env:
    - PATH
    - PYTHONPATH
    - LD_LIBRARY_PATH
    - OSPL_HOME
    - PYTHON_BUILD_VERSION
    - PYTHON_BUILD_LOCATION
    - TS_CONFIG_ATCALSYS_DIR
    - LSST_DDS_DOMAIN

test:
  requires:
    - ts-conda-build =0.3
    - ts-dds
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - ts-tcpip
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - py.test

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-salobj
    - ts-tcpip
